version: '3'
services:
  # db:
  #   image: postgres
  #   container_name: postgres
  #   ports:
  #     - 5432:5432
  #     # volumes:
  #     # - ./gp_data:/var/lib/postgresql/data/pgdata
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: docker_test
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   restart: always
  app_flask:
    image: dockerflask
    container_name: app_flask
    ports:
      - 5000:5000
    # environment:
    #   POSTGRES_HOST: db
    restart: always
    # links:
      # - db
  nginx_flask:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app_flask
    ports:
      - 8989:8989
